# This is a basic workflow to help you get started with Actions

name: Update Brew Info

on:
  schedule:
    # 月曜日の 11:00 (JST) に処理を実行する。
    # UTC の 02:00 は JST だと 11:00 。
    - cron: '* * * * *'

jobs:
  build:
    name: test
    steps:
      - name: hello world
        run: echo Hello, world!
